### ISSUE TITLE
Basic Map Outline

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Outline#1]
Hi Kevin,
Here is the basic map generation outline--hopefully this is what you meant. Let me know what I should add in, or if I should keep working on the code in the Upper_Yaquina_Figures repository. Thanks!

**Comment by kbrannan** [comment]
I made some changes check out the code at the link below. Check out the history to see the commit message
https://github.com/Creutzx/Outline/blob/kmb_run/Upper_Yaquina_Outline.py

**Comment by Creutzx** [comment]
This all makes sense to me. I'm still having trouble understanding what I'm trying to cycle through when I write the for loop. 

Is it different data frames? (so that there would be the Watershed dataframe, plus the others that will be added to the .mxd document)

Or am I trying to update the data frame with shapefiles I access with the for loop?

Or maybe I'm on the wrong track here.

**Comment by kbrannan** [comment]
Has this issue been resolved? If so, plese close
