### ISSUE TITLE
Attempt to add soils .lyr

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Outline#2]
I tried adding a soils layer to the map document, but am getting an error on this line for the saveACopy command.

https://github.com/Creutzx/Outline/blob/e9df75e201355cb5f50da05e77dd3c0ffbbd7704/Upper_Yaquina_Outline.py#L25

**Comment by kbrannan** [comment]
I made some changes and it runs. Checkout the version it in the "saveacopy_kmb" branch. 
The specifc changes are below
https://github.com/Creutzx/Outline/blob/721a4097a7cb8551c950912bd94f30970f0af5dd/Upper_Yaquina_Outline.py#L25-L28

**Comment by kbrannan** [comment]
Has this issue been resolved? If so, plese close
