### ISSUE TITLE
changing layers and exporting

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/Outline#3]
Hi Kevin,

I haven't looked at what you sent me yesterday, but I thought I should post the code I've been working on for cycling through the different layers, and exporting the different maps as .png files. I'm getting an error on this line:

https://github.com/Creutzx/Outline/blob/f714bf2a0cc99d473399ed4a834d00ea5db726f5/Map_Cycle.py#L26

the error message is:
AttributeError: PageLayoutObject: Error in executing ExportToPNG
Attempt to close invalid cell layer channel (CellLyrChannelClose)

Right now, I'll plan to start looking at the saveacopy_kmb branch you sent me yesterday afternoon.

Thanks!

**Comment by kbrannan** [comment]
There were two fixes that addressed the error. 
The first was to the path. I added the "TMDL" folder tot the path:
https://github.com/Creutzx/Outline/blob/d14d152277a179d7e41a3669ed37f99876618adb/Map_Cycle.py#L5
The next fix was adding a "\" to the creation of the path+filename
https://github.com/Creutzx/Outline/blob/d14d152277a179d7e41a3669ed37f99876618adb/Map_Cycle.py#L23

The code runs now and create the different maps in PNG files.

With respect to your question about what you are cycling through in the for-loop, you are turning on/off the visiability of layers named in "lyrList". These layers are in the data.frame "df". You define what data frame to use in line 9 and specify using the first data frame "0" in the mapdoc. Let me know if this explanation helps.

**Comment by Creutzx** [comment]
It does. 

So does this version of the map production code seem like the direction we should proceed with?

If so, then it looks like I'll need to do some work on having the code update the map titles (or maybe we'd want to leave them off and add them later in word?)

**Comment by kbrannan** [comment]
Yep, this is the approach we want to use. Yes, we will put the map titles in the captions of the figures in word, so don't includ the map titles in the graphics files. 
This looks good.
I am going to take a look at the code you have and make some changes to the organization. I will start a neww branch and post an issue for you to review when I am done.

Great work!

**Comment by Creutzx** [comment]
Thanks! Sounds good--it looks like there will also be some work to do on the ArcMap side of the equation. I'd like to get your input on how you'd like them to look, or if you're busy I can come up with a layout.

**Comment by kbrannan** [comment]
Sounds good. 
For the MapDoc side, create a few examlpes of what you think the maps should look like. Create these as seperate files and prefereably using different layer files for the symbology. Then send me links to the mxd files.

**Comment by Creutzx** [comment]
OK, I'll get to work on that. My first idea for layout is to create maps that look like those created by tetra tech for their report. For example:

![image](https://user-images.githubusercontent.com/32490475/35072002-be611d6e-fb97-11e7-8961-0992ccaa5704.png)

I thought I should mention it in case you have any strong opinions on their layout.

**Comment by kbrannan** [comment]
That's good. Leave out the logo and title information

**Comment by Creutzx** [comment]
Hi Kevin,

Here's one example map I came up with. I'll try some different layouts and send you links to those files as well.

U:\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_BC_Example_Export.mxd

It occurs to me that since we are trying to get this set up to produce all future TMDL maps, the layout could benefit from some advanced cartography.

**Comment by kbrannan** [comment]
I will take a look at the map doc.

What do you mean by adnaced cartogrpahy?

**Comment by Creutzx** [comment]
Design and presentation. Not anything having to do with the information content.

**Comment by Creutzx** [comment]
Here's another:

U:\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_BC_Example_Export2.mxd

**Comment by kbrannan** [comment]
Check out the modifications I made to 

\\deqhq1\tmdl\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_BC_Example_Elevationt.mxd
Some general comments:

- Put the name of what is being diplayed in the Map Doc file name (Elevation in this case)
-  Don't use red/greene for contrais in map becuase colorblind people will nat see this contrast
- Only put the features that are being used in the map in the map doc file.
- Put North arrow and scale at bottom of map
- Use the location in state data fame once for a general map and not in subsequent maps that focus on specific information

**Comment by Creutzx** [comment]
Here's another:

U:\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_BC_Example_Export2.mxd

**Comment by Creutzx** [comment]
Hi Kevin, here's another example map, this time for geology.

\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_BC_Example_Geology.mxd

This is assuming that you'd like to proceed with the simplified map design (e.g., no borders, no text boxes, etc.)

Overall, I wanted to check in with you about the different tasks I'm working on, and how I should be prioritizing them. Did you want me to keep working on the maps, or did you want me to take another look at the narrative part of the front material. (Since it's been a couple of weeks, I could look at it with fresh eyes.)

Thanks and let me know if there's anything else!

**Comment by kbrannan** [comment]
Hey Brian,

Use this map doc as the starting pioint for your maps:
\\deqhq1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_Layout_template_KMB20180123.mxd

Add the layers for the specifc figure (elevation, soils, precipitation, ...) to the botton of the data frame list. This will provide a consitent look to each map. Only include the layers displayed in the figure in the map doc file. 

Use a single layer to display data whenever possible. Try not to create seperate layers to differentiate data characteristics, like in the geology exmaple you provided with a seperate layer for Unconsolidated Sediment, Volcanic Rock, and Sedimentary Rock. 

Rework the elevation, precip and geology figures using the map doc template given above and these 
directions.

**Comment by Creutzx** [comment]
The file is ready, it contains Land Management, Land Cover, Precipitation, Elevation, and Soils. The precipitation and land cover layers are rasters, and I made a masking shapefile to hide the area outside the watershed. Let me know if you want me to deal with those some other way.

**Comment by Creutzx** [comment]
I also wanted to check in with you about the map generation code, and the narrative parts of the front material. You mentioned that you wanted to make some changes to the organization of the code; and I wanted to see if I should go through the writing again if you haven't already taken a look at that. There's usually a few changes I can make after not looking at it for a while.

**Comment by Creutzx** [comment]
Hi Kevin, I finished those .mxd files for: Land Management, Land Cover, Precipitation, Elevation, Geology, and Soils. The precipitation raster has a bit of a jagged edge, and I wanted to ask if I should make a mask for that, or address it some other way.

**Comment by kbrannan** [comment]
These look good. Let's work a specific chamnge via code. I will start a new issue describing it.
