### ISSUE TITLE
Change name of elevation layer

### ISSUE THREAD

**Issue by kbrannan** [Creutzx/Outline#4]
Use the map doc you created that contains the elevation data given in the path-file below. 
Write a pyhton script that changes the name of the elevation layer from "up_yaq_elev" to "Elevation" then save the updated map doc file.

\\\\deqhq1\tmdl\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_Layout_Elevation_BRC.mxd

**Comment by Creutzx** [comment]
This worked, although I wasn't sure if you wanted this to create a new .mxd file. Should I start a new repository or branch for this?

`import arcpy

mxd = arcpy.mapping.MapDocument(r'\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_Layout_Elevation_BRC.mxd')
#current view?
df = arcpy.mapping.ListDataFrames(mxd)[0]
lyr = arcpy.mapping.ListLayers(mxd, "", df)
for lyr in arcpy.mapping.ListLayers(mxd):
    if lyr.name == "up_yaq_elev":
        lyr.name = "Elevation"
        lyr.visible = True

arcpy.RefreshTOC()
arcpy.RefreshActiveView()
mxd.save()`

**Comment by kbrannan** [comment]
Great, add the py file with the above code to the github repo.
