### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by kbrannan** [Creutzx/Outline#5]
I saw there several branches in this repo. It's time to do some house keeping. Check to see which branch is most up to date and has the version of code you want and remove the other branches. It may not be that simple. You may need to do several pull requests to get all the cjanges you want in the code. Take a look and let me know what you find

**Comment by Creutzx** [comment]
Sounds good, I'll get to work on that. I was considering creating a new repository for the snippet of code I just wrote, since it doesn't seem to fit into this one.

**Comment by kbrannan** [comment]
ok, close this issue when you think it's done

**Comment by Creutzx** [comment]
The master is now up to date with the latest version.
